openapi: "3.0.0"
info:
  version: 1.0.0
  title: Sourcify API
  description: API to interact with Sourcify
  license:
    name: MIT
    url: https://github.com/ethereum/sourcify/blob/master/LICENSE
servers:
  - url: https://sourcify.dev/server
    description: Production server
  - url: https://staging.sourcify.dev/server
    description: Staging server
  - url: http://localhost:5555
    description: Local development server address on default port 5555.
tags:
  - name: Stateless Verification
    description: Main verification endpoints
  - name: Repository
    description: Access to already verified contracts and files
  - name: Session Verification
    description: Used by the Sourcify UI to verify contracts. Not intended for external usage. Will require CORS.
paths:
  /verify:
    $ref: "server/controllers/verification/verify/stateless/verify.stateless.paths.yaml#/paths/~1verify"
  /verify/etherscan:
    $ref: "server/controllers/verification/etherscan/stateless/etherscan.stateless.paths.yaml#/paths/~1verify~1etherscan"
  /verify/solc-json:
    $ref: "server/controllers/verification/solc-json/stateless/solc-json.stateless.paths.yaml#/paths/~1verify~1solc-json"
  /check-all-by-addresses:
    $ref: "server/controllers/repository/check-all-by-addresses.stateless.paths.yaml#/paths/~1check-all-by-addresses"
  /check-by-addresses:
    $ref: "server/controllers/repository/check-by-addresses.stateless.paths.yaml#/paths/~1check-by-addresses"
  /files/any/{chain}/{address}:
    $ref: "server/controllers/repository/get-source-files-all.stateless.paths.yaml#/paths/~1files~1any~1{chain}~1{address}"
  /files/{chain}/{address}:
    $ref: "server/controllers/repository/get-source-files-full.stateless.paths.yaml#/paths/~1files~1{chain}~1{address}"
  /repository/contracts/{full_match | partial_match}/{chain}/{address}/{filePath}:
    $ref: "server/controllers/repository/get-file-static.stateless.paths.yaml#/paths/~1repository~1contracts~1{full_match | partial_match}~1{chain}~1{address}~1{filePath}"
  /files/contracts/{chain}:
    $ref: "server/controllers/repository/get-contract-addresses-all.stateless.paths.yaml#/paths/~1files~1contracts~1{chain}"
  /files/tree/any/{chain}/{address}:
    $ref: "server/controllers/repository/get-file-tree-all.stateless.paths.yaml#/paths/~1files~1tree~1any~1{chain}~1{address}"
  /files/tree/{chain}/{address}:
    $ref: "server/controllers/repository/get-file-tree-full.stateless.paths.yaml#/paths/~1files~1tree~1{chain}~1{address}"
  /session/data:
    $ref: "server/controllers/verification/session-state/data.session-state.paths.yaml#/paths/~1session~1data"
  /session/clear:
    $ref: "server/controllers/verification/session-state/clear.session-state.paths.yaml#/paths/~1session~1clear"
  /session/input-files:
    $ref: "server/controllers/verification/session-state/input-files.session-state.paths.yaml#/paths/~1session~1input-files"
  /session/input-contract:
    $ref: "server/controllers/verification/session-state/input-contract.session-state.paths.yaml#/paths/~1session~1input-contract"
  /session/verify-checked:
    $ref: "server/controllers/verification/verify/session/verify.session.paths.yaml#/paths/~1session~1verify-checked"
  /session/input-solc-json:
    $ref: "server/controllers/verification/solc-json/session/solc-json.session.paths.yaml#/paths/~1session~1input-solc-json"
  /session/verify/etherscan:
    $ref: "server/controllers/verification/etherscan/session/etherscan.session.paths.yaml#/paths/~1session~1verify~1etherscan"
  /change-log-level:
    post:
      summary: Change the logging level of the application
      description: Allows changing the logging level dynamically at runtime for the application. Requires Basic Authentication.
      tags:
        - Logging
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - level
              properties:
                level:
                  type: string
                  description: The new logging level to set.
                  enum: [error, warn, info, debug, silly]
            examples:
              change to debug:
                value: 
                  level: "debug"
              change to info:
                value: 
                  level: "info"
      responses:
        "200":
          description: The logging level was successfully changed.
          content:
            text/plain:
              schema:
                type: string
                example: "Logging level changed to: debug"
        "400":
          description: Bad request (e.g., invalid logging level provided).
        "401":
          description: Unauthorized (missing or invalid Basic Authentication credentials).

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
